services: 
    intern_db: 
        image: mongo:latest
        container_name: intern-db
        restart: unless-stopped
        ports: 
            - 27017:27017
        env_file: .env
        volumes: 
            - ./datas:/data/db
            - ./entrypoint/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
